source_dir = "protos"
destination_dir = "objects"
html_dir = "templates"
static_dir = "static"

PROTO_FILE_SUFFIX = ".proto"
PYTHON_FILE_SUFFIX = ".py"
HTML_FILE_SUFFIX = ".html"

PYTHON_GENERATED_SUFFIX = "_pb2"
PROTO_TYPE_PREFIX = "TYPE_"

''' Returns a list of the fields on an object generated by Protocol Buffers. '''
def get_proto_fields(self, object_):
    return object_.DESCRIPTOR.fields


''' Returns the name of the type object '''
def get_name(self, object_):
    return object_.__class__.__name__